// rules.js

// NOUVEL AJOUT : Base de données des unités par faction et leur coût.
const factionUnits = {
    "Adepta Sororitas": [
        { name: "Aestred Thurga et Agathae Dolan", cost: 85 },
        { name: "Arco-flagellants", cost: 45 },
        { name: "Castigator", cost: 160 },
        { name: "Célestes Sacro-saintes", cost: 70 },
        { name: "Chanoinesse", cost: 50 },
        { name: "Chanoinesse à Réacteur Dorsal", cost: 75 },
        { name: "Démonifuge", cost: 85 },
        { name: "Dialogus", cost: 40 },
        { name: "Dogmata", cost: 45 },
        { name: "Escouade de Sœurs de Bataille", cost: 105 },
        { name: "Escouade de Sœurs Novices", cost: 100 },
        { name: "Escouade Dominion", cost: 115 },
        { name: "Escouade Repentia", cost: 75 },
        { name: "Escouade Retributor", cost: 115 },
        { name: "Escouade Séraphine", cost: 80 },
        { name: "Escouade Zéphyrine", cost: 80 },
        { name: "Exo-harnais Parangon", cost: 210 },
        { name: "Exorcist", cost: 210 },
        { name: "Hospitalière", cost: 50 },
        { name: "Imagifère", cost: 65 },
        { name: "Immolator", cost: 115 },
        { name: "Junith Eruita", cost: 80 },
        { name: "Machines de Pénitence", cost: 75 },
        { name: "Mortificatrices", cost: 70 },
        { name: "Morvenn Vahl", cost: 170 },
        { name: "Palatine", cost: 50 },
        { name: "Prêtre du Ministorum", cost: 50 },
        { name: "Rhino Sororitas", cost: 75 },
        { name: "Sainte Célestine", cost: 160 },
        { name: "Sanctificateurs", cost: 100 },
        { name: "Triomphe de Sainte Katherine", cost: 235 }
    ],
    "Adeptus Custodes": [
        { name: "Aleya", cost: 65 },
        { name: "Capitaine-rempart", cost: 130 },
        { name: "Capitaine-rempart en Armure Terminator Allarus", cost: 130 },
        { name: "Capitaine-rempart sur Motojet Dawneagle", cost: 150 },
        { name: "Champion des Lames", cost: 120 },
        { name: "Chevalière-centura", cost: 55 },
        { name: "Custodiens Allarus", cost: 120 },
        { name: "Dreadnought Contemptor Vénérable", cost: 170 },
        { name: "Gardes Custodiens", cost: 170 },
        { name: "Land Raider Vénérable", cost: 240 },
        { name: "Praetors Vertus", cost: 150 },
        { name: "Prosecutors", cost: 40 },
        { name: "Répurgatrices", cost: 50 },
        { name: "Rhino Anathema Psykana", cost: 75 },
        { name: "Trajann Valoris", cost: 140 },
        { name: "Valerian", cost: 110 },
        { name: "Veilleurs Custodiens", cost: 210 },
        { name: "Vigilators", cost: 50 },
        { name: "Agamatus Custodians", cost: 225 },
        { name: "Aquilon Custodians", cost: 195 },
        { name: "Ares Gunship", cost: 580 },
        { name: "Caladius Grav-tank", cost: 215 },
        { name: "Contemptor-Achillus Dreadnought", cost: 155 },
        { name: "Contemptor-Galatus Dreadnought", cost: 165 },
        { name: "Coronus Grav-carrier", cost: 200 },
        { name: "Custodian Guard with Adrasite and Pyrithite Spears", cost: 250 },
        { name: "Orion Assault Dropship", cost: 690 },
        { name: "Pallas Grav-attack", cost: 105 },
        { name: "Sagittarum Custodians", cost: 225 },
        { name: "Telemon Heavy Dreadnought", cost: 225 },
        { name: "Venatari Custodians", cost: 165 }
    ],
    "Adeptus Mechanicus": [
        { name: "Archéoptère Fusilave", cost: 160 },
        { name: "Archéoptère Stratoraptor", cost: 185 },
        { name: "Archéoptère Transvector", cost: 150 },
        { name: "Belisarius Cawl", cost: 135 },
        { name: "Brécheurs Kataphron", cost: 160 },
        { name: "Compilateur Cybernétique", cost: 35 },
        { name: "Corrodeurs Sicariens", cost: 75 },
        { name: "Désintégrateur Skorpius", cost: 165 },
        { name: "Destructeurs Kataphron", cost: 105 },
        { name: "Dragons Sydoniens avec Jezzail à Radium", cost: 55 },
        { name: "Dragons Sydoniens avec Lances Taser", cost: 65 },
        { name: "Électroprêtres Corpuscarii", cost: 65 },
        { name: "Électroprêtres Fulgurites", cost: 70 },
        { name: "Ferro-échassiers Ballistarii", cost: 70 },
        { name: "Glisseur Skorpius", cost: 85 },
        { name: "Hussards Serberys", cost: 60 },
        { name: "Infiltrateurs Sicariens", cost: 70 },
        { name: "Maréchal Skitarii", cost: 35 },
        { name: "Onagre des Dunes", cost: 155 },
        { name: "Patrouilleurs Skitarii", cost: 95 },
        { name: "Rangers Skitarii", cost: 85 },
        { name: "Robots Kastelan", cost: 180 },
        { name: "Skatros Sydonien", cost: 50 },
        { name: "Soufredogues Serberys", cost: 55 },
        { name: "Stérilisateurs Pteraxii", cost: 80 },
        { name: "Technaugure", cost: 55 },
        { name: "Technoarchéologue", cost: 45 },
        { name: "Technoprêtre Dominus", cost: 65 },
        { name: "Technoprêtre Manipulus", cost: 60 },
        { name: "Vautours Pteraxii", cost: 70 }
    ],
    "Adeptus Titanicus": [
        { name: "Reaver Titan", cost: 2200 },
        { name: "Warbringer Nemesis Titan", cost: 2600 },
        { name: "Warhound Titan", cost: 1100 },
        { name: "Warlord Titan", cost: 3500 }
    ],
    "Astra Militarum": [
        { name: "Aquilons du Tempestus", cost: 100 },
        { name: "Baneblade", cost: 480 },
        { name: "Banehammer", cost: 450 },
        { name: "Banesword", cost: 480 },
        { name: "Basilisk", cost: 140 },
        { name: "Batterie d'Artillerie", cost: 110 },
        { name: "Castellan Cadien", cost: 55 },
        { name: "Cavaliers d'Attila", cost: 60 },
        { name: "Cavaliers de Krieg", cost: 60 },
        { name: "Char de Combat Leman Russ", cost: 185 },
        { name: "Char de Combat Rogal Dorn", cost: 240 },
        { name: "Chimera", cost: 85 },
        { name: "Combattants des Jungles de Catachan", cost: 65 },
        { name: "Commandant de Leman Russ", cost: 235 },
        { name: "Commandant de Rogal Dorn", cost: 265 },
        { name: "Commissaire", cost: 30 },
        { name: "Death Korps de Krieg", cost: 65 },
        { name: "Deathstrike", cost: 145 },
        { name: "Doomhammer", cost: 445 },
        { name: "Équipe d'Artillerie", cost: 95 },
        { name: "Escouade d'Armes Lourdes Cadienne", cost: 65 },
        { name: "Escouade d'Armes Lourdes de Catachan", cost: 65 },
        { name: "Escouade d'Armes Lourdes de Krieg", cost: 75 },
        { name: "Escouade d'État-Major Cadienne", cost: 65 },
        { name: "Escouade d'État-Major de Catachan", cost: 65 },
        { name: "Escouade d'Etat-Major de Krieg", cost: 65 },
        { name: "Escouade d'État-Major du Militarum Tempestus", cost: 85 },
        { name: "Escouade d'Ogryns", cost: 60 },
        { name: "Escouade de Taurogryns", cost: 100 },
        { name: "Fantômes de Gaunt", cost: 110 },
        { name: "Garde du Corps Ogryn", cost: 40 },
        { name: "Hellhammer", cost: 450 },
        { name: "Hellhound", cost: 125 },
        { name: "Hydra", cost: 95 },
        { name: "Kasrkins", cost: 110 },
        { name: "Leman Russ Demolisher", cost: 190 },
        { name: "Leman Russ Eradicator", cost: 170 },
        { name: "Leman Russ Executioner", cost: 170 },
        { name: "Leman Russ Exterminator", cost: 180 },
        { name: "Leman Russ Punisher", cost: 150 },
        { name: "Leman Russ Vanquisher", cost: 145 },
        { name: "Ligne de Défense Aegis", cost: 145 },
        { name: "Manticore", cost: 165 },
        { name: "Nork Deddog", cost: 60 },
        { name: "Prêtre du Ministorum", cost: 35 },
        { name: "Psyker Primaris", cost: 60 },
        { name: "Pupilles du Tempestus", cost: 70 },
        { name: "Ratlings", cost: 60 },
        { name: "Sapeurs de Krieg", cost: 70 },
        { name: "Seigneur Solaire Leontus", cost: 150 },
        { name: "Seigneur-Maréchal Dreir", cost: 100 },
        { name: "Sentinel Blindés", cost: 65 },
        { name: "Sentinel de Reconnaissance", cost: 55 },
        { name: "Shadowsword", cost: 440 },
        { name: "Sly Marbo", cost: 55 },
        { name: "Stormlord", cost: 460 },
        { name: "Stormsword", cost: 495 },
        { name: "Taurox", cost: 75 },
        { name: "Taurox Primus", cost: 90 },
        { name: "Technaugure", cost: 45 },
        { name: "Troupes de Choc Cadiennes", cost: 65 },
        { name: "Ursula Creed", cost: 85 },
        { name: "Valkyrie", cost: 190 },
        { name: "Wyvern", cost: 110 },
        { name: "Avenger Strike Fighter", cost: 130 },
        { name: "Cyclops Demolition Vehicle", cost: 25 }
    ],
    "Black Templars": [
        { name: "Castellan", cost: 60 },
        { name: "Chapelain Grimaldus", cost: 120 },
        { name: "Escouade Crusader", cost: 85 },
        { name: "Escouade Crusader Primaris", cost: 150 },
        { name: "Frères d'Épée Primaris", cost: 140 },
        { name: "Gladiator Lancer des Black Templars", cost: 170 },
        { name: "Gladiator Reaper des Black Templars", cost: 170 },
        { name: "Gladiator Valiant des Black Templars", cost: 170 },
        { name: "Grand Sénéchal Helbrecht", cost: 120 },
        { name: "Impulsor des Black Templars", cost: 90 },
        { name: "Le Champion de l'Empereur", cost: 75 },
        { name: "Repulsor des Black Templars", cost: 190 },
        { name: "Repulsor Executioner des Black Templars", cost: 230 },
        { name: "Sénéchal", cost: 75 }
    ],
    "Blood Angels": [
        { name: "Astorath", cost: 95 },
        { name: "Capitaine de la Compagnie de la Mort", cost: 70 },
        { name: "Capitaine de la Compagnie de la Mort à Réacteur Dorsal", cost: 75 },
        { name: "Capitaine des Blood Angels", cost: 80 },
        { name: "Commandeur Dante", cost: 120 },
        { name: "Dreadnought de la Compagnie de la Mort", cost: 160 },
        { name: "Garde Sanguinienne", cost: 110 },
        { name: "Le Sanguinor", cost: 140 },
        { name: "Lemartes", cost: 100 },
        { name: "Maître Archiviste Méphiston", cost: 120 },
        { name: "Marines de la Compagnie de la Mort", cost: 85 },
        { name: "Marines de la Compagnie de la Mort à Réacteurs Dorsaux", cost: 120 },
        { name: "Marines de la Compagnie de la Mort avec Fusils Bolters", cost: 85 },
        { name: "Predator Baal", cost: 125 },
        { name: "Prêtre Sanguinien", cost: 75 }
    ],
    "Space Marines": [
        { name: "Adrax Agatone", cost: 85 },
        { name: "Apothicaire", cost: 50 },
        { name: "Apothicaire Biologis", cost: 70 },
        { name: "Archiviste", cost: 65 },
        { name: "Archiviste en Armure Phobos", cost: 70 },
        { name: "Archiviste en Armure Terminator", cost: 75 },
        { name: "Bunker Hammerfall", cost: 175 },
        { name: "Capitaine", cost: 80 },
        { name: "Capitaine à Réacteur Dorsal", cost: 75 },
        { name: "Capitaine en Armure Gravis", cost: 80 },
        { name: "Capitaine en Armure Phobos", cost: 70 },
        { name: "Capitaine en Armure Terminator", cost: 95 },
        { name: "Capitaine Sicarius", cost: 85 },
        { name: "Chapelain", cost: 60 },
        { name: "Chapelain à Moto", cost: 75 },
        { name: "Chapelain à Réacteur Dorsal", cost: 75 },
        { name: "Chapelain en Armure Terminator", cost: 75 },
        { name: "Darnath Lysander", cost: 100 },
        { name: "Doyen", cost: 50 },
        { name: "Doyen Bladeguard", cost: 45 },
        { name: "Doyen en Armure Terminator", cost: 75 },
        { name: "Dreadnought", cost: 135 },
        { name: "Dreadnought Ballistus", cost: 140 },
        { name: "Dreadnought Brutalis", cost: 160 },
        { name: "Dreadnought Redemptor", cost: 210 },
        { name: "Escorteur Stormraven", cost: 280 },
        { name: "Escorteur Stormtalon", cost: 165 },
        { name: "Escouade Aggressor", cost: 100 },
        { name: "Escouade Centurion Devastator", cost: 165 },
        { name: "Escouade d'Assaut Centurion", cost: 150 },
        { name: "Escouade d'Assaut Intercessor", cost: 75 },
        { name: "Escouade d'Assaut Terminator", cost: 180 },
        { name: "Escouade de Vétérans Bladeguards", cost: 80 },
        { name: "Escouade de Vétérans Sternguards", cost: 100 },
        { name: "Escouade de Vétérans Vanguards à Réacteurs Dorsaux", cost: 95 },
        { name: "Escouade Desolator", cost: 200 },
        { name: "Escouade Devastator", cost: 120 },
        { name: "Escouade Eliminator", cost: 85 },
        { name: "Escouade Eradicator", cost: 100 },
        { name: "Escouade Hellblaster", cost: 110 },
        { name: "Escouade Inceptor", cost: 120 },
        { name: "Escouade Incursor", cost: 80 },
        { name: "Escouade Infernus", cost: 90 },
        { name: "Escouade Infiltrator", cost: 100 },
        { name: "Escouade Intercessor", cost: 80 },
        { name: "Escouade Lourde Intercessor", cost: 100 },
        { name: "Escouade Outrider", cost: 80 },
        { name: "Escouade Reiver", cost: 80 },
        { name: "Escouade Scout", cost: 70 },
        { name: "Escouade Suppressor", cost: 75 },
        { name: "Escouade Tactique", cost: 140 },
        { name: "Escouade Terminator", cost: 170 },
        { name: "Exo-harnais Tactique Invictor", cost: 125 },
        { name: "Gladiator Lancer", cost: 160 },
        { name: "Gladiator Reaper", cost: 160 },
        { name: "Gladiator Valiant", cost: 160 },
        { name: "Héros de Compagnie", cost: 105 },
        { name: "Impulsor", cost: 80 },
        { name: "Intercepteur Stormhawk", cost: 155 },
        { name: "Intercessors d'Assaut à Réacteurs Dorsaux", cost: 90 },
        { name: "Judicateur", cost: 70 },
        { name: "Kayvaan Shrike", cost: 100 },
        { name: "Kor'sarro Khan", cost: 70 },
        { name: "Land Raider", cost: 240 },
        { name: "Land Raider Crusader", cost: 220 },
        { name: "Land Raider Redeemer", cost: 85 },
        { name: "Lieutenant", cost: 65 },
        { name: "Lieutenant avec Arme Combinée", cost: 70 },
        { name: "Lieutenant en Armure Phobos", cost: 55 },
        { name: "Lieutenant en Armure Reiver", cost: 55 },
        { name: "Lieutenant Titus", cost: 70 },
        { name: "Maître Archiviste Tigurius", cost: 75 },
        { name: "Marneus Calgar", cost: 200 },
        { "name": "Module de Largage", cost: 70 },
        { name: "Pedro Kantor", cost: 90 },
        { name: "Predator Annihilator", cost: 135 },
        { name: "Predator Destructor", cost: 140 },
        { name: "Quad Invader", cost: 60 },
        { name: "Razorback", cost: 95 },
        { name: "Repulsor", cost: 180 },
        { name: "Repulsor Executioner", cost: 220 },
        { name: "Révérend de Fer Feirros", cost: 95 },
        { name: "Rhino", cost: 75 },
        { name: "Roboute Guilliman", cost: 320 },
        { name: "Servo-tourelles Firestrike", cost: 75 },
        { name: "Storm Speeder Hailstrike", cost: 115 },
        { name: "Storm Speeder Hammerstrike", cost: 125 },
        { name: "Storm Speeder Thunderstrike", cost: 150 },
        { name: "Techmarine", cost: 55 },
        { name: "Tor Garadon", cost: 90 },
        { name: "Uriel Ventris", cost: 95 },
        { name: "Vindicator", cost: 185 },
        { name: "Vulkan He'stan", cost: 100 },
        { name: "Whirlwind", cost: 190 },
        { name: "Astraeus", cost: 525 },
        { name: "Thunderhawk Gunship", cost: 840 }
    ],
"Space Wolves": [
        { name: "Arjac Rockfist", cost: 95 },
        { name: "Björn Main Funeste", cost: 170 },
        { name: "Cavalerie sur Loups Tonnerre", cost: 100 },
        { name: "Chasseurs Gris", cost: 180 },
        { name: "Chef de Bataille Garde Loup", cost: 65 },
        { name: "Dreadnought Vénérable", cost: 140 },
        { name: "Dreadnought Wulfen", cost: 145 },
        { name: "Griffes Sanglantes", cost: 135 },
        { name: "Logan Grimnar", cost: 110 },
        { name: "Loups Fenrissiens", cost: 40 },
        { name: "Murderfang", cost: 160 },
        { name: "Njál Stormcaller", cost: 85 },
        { name: "Preneurs de Têtes Gardes Loups", cost: 85 },
        { name: "Prêtre de Fer", cost: 60 },
        { name: "Prêtre Loup", cost: 70 },
        { name: "Ragnar Blackmane", cost: 90 },
        { name: "Terminators Gardes Loups", cost: 170 },
        { name: "Ulrik le Tueur", cost: 70 },
        { name: "Wulfens", cost: 85 },
        { name: "Wulfens avec Bouclier Storm", cost: 100 }
    ],
    "T'au Empire": [
        { name: "Bombardier Sun Shark", cost: 160 },
        { name: "Carnivores Kroots", cost: 65 },
        { name: "Cavaliers Krootox", cost: 40 },
        { name: "Char Hammerhead", cost: 145 },
        { name: "Char Sky Ray", cost: 140 },
        { name: "Chasseur Razorshark", cost: 170 },
        { name: "Chiens Kroots", cost: 40 },
        { name: "Commandant en Exo-armure Coldstar", cost: 95 },
        { name: "Commandant en Exo-armure Enforcer", cost: 80 },
        { name: "Commandant Farsight", cost: 95 },
        { name: "Commandante Shadowsun", cost: 100 },
        { name: "Darkstrider", cost: 60 },
        { name: "Devilfish", cost: 85 },
        { name: "Droneport Tidewall", cost: 85 },
        { name: "Équipe d'Attaque", cost: 75 },
        { name: "Équipe de Brécheurs", cost: 100 },
        { name: "Équipe de Cibleurs", cost: 90 },
        { name: "Équipe de Tir Furtive", cost: 70 },
        { name: "Éthéré", cost: 50 },
        { name: "Exo-armure Ghostkeel", cost: 160 },
        { name: "Exo-armure Riptide", cost: 190 },
        { name: "Exo-armures Broadside", cost: 90 },
        { name: "Crisis Fireknife Exo-armures", cost: 130 },
        { name: "Exo-armures Crisis Starscythe", cost: 110 },
        { name: "Exo-armures Crisis Sunforge", cost: 150 },
        { name: "Exo-armures Stealth", cost: 80 },
        { name: "Exorôdeurs Kroots", cost: 85 },
        { name: "Frelons Vespides", cost: 65 },
        { name: "Ligne-bouclier Tidewall", cost: 85 },
        { name: "Mentor de Guerre Kroot", cost: 50 },
        { name: "Mentor Dépeceur Kroot", cost: 45 },
        { name: "Mentor Pisteur Kroot", cost: 55 },
        { name: "Piranha", cost: 60 },
        { name: "Sabre de Feu", cost: 50 },
        { name: "Saccageurs Krootox", cost: 85 },
        { name: "Solilance Kroot", cost: 80 },
        { name: "Stormsurge", cost: 400 },
        { name: "Tourelle Tidewall", cost: 90 },
        { name: "AX-1-0 Tiger Shark", cost: 315 },
        { name: "Manta", cost: 2100 },
        { name: "Ta'unar Supremacy Armour", cost: 790 },
        { name: "Tiger Shark", cost: 325 }
    ],
    "Thousand Sons": [
        { name: "Ahriman", cost: 100 },
        { name: "Chaman Tzaangor", cost: 55 },
        { name: "Ferrocentaurus", cost: 140 },
        { name: "Ferrocerberus", cost: 130 },
        { name: "Land Raider du Chaos", cost: 240 },
        { name: "Magnus le Rouge", cost: 420 },
        { name: "Maître Infernal", cost: 85 },
        { name: "Marines Rubricae", cost: 100 },
        { name: "Métabrutus", cost: 110 },
        { name: "Métadrak", cost: 215 },
        { name: "Mutalithe à Vortex", cost: 160 },
        { name: "Predator Annihilator du Chaos", cost: 130 },
        { name: "Predator Destructor du Chaos", cost: 140 },
        { name: "Prince Démon de Tzeentch", cost: 180 },
        { name: "Prince Démon de Tzeentch Ailé", cost: 170 },
        { name: "Profanateur", cost: 165 },
        { name: "Rejetons du Chaos", cost: 65 },
        { name: "Rhino du Chaos", cost: 90 },
        { name: "Robots Sekhetar", cost: 90 },
        { name: "Sorcier", cost: 75 },
        { name: "Sorcier en Armure Terminator", cost: 85 },
        { name: "Sorcier Exalté", cost: 80 },
        { name: "Sorcier Exalté sur Disque de Tzeentch", cost: 100 },
        { name: "Terminators du Scarabée Occulte", cost: 180 },
        { name: "Tzaangors", cost: 70 },
        { name: "Tzaangors Éclairés", cost: 50 },
        { name: "Tzaangors Éclairés avec Grands Arcs Scelle-destin", cost: 50 },
        { name: "Vindicator du Chaos", cost: 185 }
    ],
    "Tyranids": [
        { name: "Assimilatrice Norne", cost: 275 },
        { name: "Barbgaunts", cost: 55 },
        { name: "Biovores", cost: 50 },
        { name: "Bondisseurs de Von Ryan", cost: 70 },
        { name: "Carnifex", cost: 115 },
        { name: "Emissaire Norne", cost: 260 },
        { name: "Exocrine", cost: 140 },
        { name: "Gardes des Ruches", cost: 90 },
        { name: "Gardes Tyranides", cost: 80 },
        { name: "Gargouilles", cost: 85 },
        { name: "Genestealers", cost: 75 },
        { name: "Génocrate", cost: 80 },
        { name: "Guerriers Tyranides avec Bio-armes de Mêlée", cost: 75 },
        { name: "Guerriers Tyranides avec Bio-armes de Tir", cost: 65 },
        { name: "Harpie", cost: 215 },
        { name: "Haruspex", cost: 125 },
        { name: "Hormagaunts", cost: 65 },
        { name: "La Mort Subite", cost: 80 },
        { name: "Le Maître des Essaims", cost: 220 },
        { name: "Le Vieux Borgne", cost: 150 },
        { name: "Lictor", cost: 60 },
        { name: "Maleceptor", cost: 170 },
        { name: "Mawloc", cost: 145 },
        { name: "Neurogaunts", cost: 45 },
        { name: "Neurolictor", cost: 80 },
        { name: "Neurotyran", cost: 105 },
        { name: "Nuées de Voraces", cost: 25 },
        { name: "Parasite de Mortrex", cost: 80 },
        { name: "Primat Tyranide Ailé", cost: 65 },
        { name: "Psychophage", cost: 110 },
        { name: "Pyrovores", cost: 40 },
        { name: "Rodeurs", cost: 75 },
        { name: "Spores Mines", cost: 55 },
        { name: "Spores Mucolides", cost: 30 },
        { name: "Sporokyste", cost: 145 },
        { name: "Termagants", cost: 60 },
        { name: "Tervigon", cost: 175 },
        { name: "Toxicrène", cost: 150 },
        { name: "Trygon", cost: 140 },
        { name: "Tueur-hurleur", cost: 135 },
        { name: "Tyran des Ruches", cost: 195 },
        { name: "Tyran des Ruches Ailé", cost: 170 },
        { name: "Tyrannocyte", cost: 105 },
        { name: "Tyrannofex", cost: 200 },
        { name: "Venomthropes", cost: 70 },
        { name: "Virago des Ruches", cost: 200 },
        { name: "Zoanthropes", cost: 100 },
        { name: "Harridan", cost: 610 },
        { name: "Hierophant", cost: 810 }
    ],
    "World Eaters": [
        { name: "Angron", cost: 385 },
        { name: "Berzerks de Khorne", cost: 180 },
        { name: "Chakhals", cost: 65 },
        { name: "Ferrocentaurus", cost: 150 },
        { name: "Ferrocerberus", cost: 150 },
        { name: "Khârn le Félon", cost: 85 },
        { name: "Land Raider du Chaos", cost: 240 },
        { name: "Maître des Exécutions", cost: 60 },
        { name: "Métabrutus", cost: 120 },
        { name: "Métadrak", cost: 200 },
        { name: "Munifisangs", cost: 85 },
        { name: "Occilié", cost: 85 },
        { name: "Octoliés", cost: 150 },
        { name: "Octoliés Exaltés", cost: 160 },
        { name: "Predator Annihilator du Chaos", cost: 145 },
        { name: "Predator Destructor du Chaos", cost: 145 },
        { name: "Prince Démon de Khorne", cost: 200 },
        { name: "Prince Démon de Khorne Ailé", cost: 180 },
        { name: "Profanateur", cost: 180 },
        { name: "Rejetons du Chaos", cost: 80 },
        { name: "Rhino du Chaos", cost: 85 },
        { name: "Seigneur des Crânes de Khorne", cost: 505 },
        { name: "Seigneur Invocatus", cost: 110 },
        { name: "Seigneur sur Juggernaut", cost: 90 },
        { name: "Terminators du Chaos", cost: 185 }
    ],
"Aeldari": [
        { name: "Araignées Spectrales", cost: 95 },
        { name: "Asurmen", cost: 135 },
        { name: "Autarque", cost: 85 },
        { name: "Autarque Sautevoie", cost: 80 },
        { name: "Avatar de Khaine", cost: 300 },
        { name: "Baharroth", cost: 115 },
        { name: "Banshees Huantes", cost: 95 },
        { name: "Bouffon Tragique", cost: 90 },
        { name: "Chasseur Écarlate", cost: 160 },
        { name: "Chasseur Fantôme Conium", cost: 155 },
        { name: "Chevalier Fantôme", cost: 435 },
        { name: "Chevalier Fantôme avec Sabre Spectral", cost: 420 },
        { name: "Conclave de Psycharques", cost: 55 },
        { name: "Corsaires Neantari", cost: 60 },
        { name: "Corsaires Neanti", cost: 80 },
        { name: "Coryphée", cost: 75 },
        { name: "Coureurs Mirages", cost: 80 },
        { name: "Dragons Flamboyants", cost: 120 },
        { name: "Eldrad Ulthran", cost: 110 },
        { name: "Éperviers Voltigeurs", cost: 85 },
        { name: "Faucheurs Noirs", cost: 90 },
        { name: "Faucon", cost: 130 },
        { name: "Fuegan", cost: 120 },
        { name: "Gardes Fantômes", cost: 170 },
        { name: "Gardiens de Choc", cost: 100 },
        { name: "Gardiens Défenseurs", cost: 100 },
        { name: "Gardiens du Vent", cost: 80 },
        { name: "Grand Prophète", cost: 70 },
        { name: "Grand Prophète Coureur Céleste", cost: 80 },
        { name: "Guerriers Fantômes", cost: 170 },
        { name: "Jain Zar", cost: 105 },
        { name: "Lances Étincelantes", cost: 110 },
        { name: "Lhykhis", cost: 120 },
        { name: "Marcheur de Guerre", cost: 85 },
        { name: "Maugan Ra", cost: 100 },
        { name: "Plateforme à Canon à Distorsion", cost: 125 },
        { name: "Plateforme à Canon à Vibrations", cost: 60 },
        { name: "Plateforme à Tisseur de Ténèbres", cost: 75 },
        { name: "Prisme de Feu", cost: 150 },
        { name: "Prophète de l'Ombre", cost: 60 },
        { name: "Psycharque", cost: 45 },
        { name: "Psycharques Coureurs Célestes", cost: 45 },
        { name: "Rangers", cost: 55 },
        { name: "Scorpions Foudroyants", cost: 85 },
        { name: "Seigneur Fantôme", cost: 140 },
        { name: "Serpent Ondoyant", cost: 125 },
        { name: "Solitaire", cost: 115 },
        { name: "Spirite", cost: 65 },
        { name: "Tisseur de Nuit", cost: 190 },
        { name: "Tisseur du Néant", cost: 125 },
        { name: "Tisseur Stellaire", cost: 80 },
        { name: "Tisseurs Célestes", cost: 95 },
        { name: "Troupe", cost: 85 },
        { name: "Vengeurs Lugubres", cost: 80 },
        { name: "Vyper", cost: 65 },
        { name: "Phantom Titan", cost: 2100 },
        { name: "Revenant Titan", cost: 1100 }
    ],
    "Chaos Daemons": [
        { name: "Autel des Crânes", cost: 105 },
        { name: "Be'lakor", cost: 375 },
        { name: "Bêtes de Nurgle", cost: 65 },
        { name: "Bourdons de la Peste", cost: 110 },
        { name: "Broyeur d'Ames", cost: 180 },
        { name: "Buveur de Sang", cost: 305 },
        { name: "Canon à Crânes", cost: 95 },
        { name: "Char Ardent", cost: 115 },
        { name: "Charnelles", cost: 110 },
        { name: "Chars Ecorcheurs", cost: 80 },
        { name: "Comique Tripier", cost: 55 },
        { name: "Démonettes", cost: 100 },
        { name: "Duc du Changement", cost: 260 },
        { name: "Epidemius", cost: 80 },
        { name: "Epitome Tortueux", cost: 100 },
        { name: "Équarrisseurs", cost: 110 },
        { name: "Falsificateur", cost: 60 },
        { name: "Fluctuarque", cost: 60 },
        { name: "Fortunarque", cost: 95 },
        { name: "Gardien des Secrets", cost: 290 },
        { name: "Grand Immonde", cost: 250 },
        { name: "Gueule Noueuse Immonde", cost: 100 },
        { name: "Horreurs Bleues", cost: 125 },
        { name: "Horreurs Roses", cost: 140 },
        { name: "Horticulous Slimux", cost: 120 },
        { name: "Hurleurs", cost: 80 },
        { name: "Incendiaire Exalté", cost: 65 },
        { name: "Incendiaires", cost: 65 },
        { name: "Infernale Séductrice", cost: 60 },
        { name: "Kairos Fateweaver", cost: 270 },
        { name: "Karanak", cost: 75 },
        { name: "Le Masque de Slaanesh", cost: 95 },
        { name: "Le Mystificateur", cost: 90 },
        { name: "Les Scribes Bleus", cost: 75 },
        { name: "Maître des Crânes", cost: 100 },
        { name: "Maître du Sang", cost: 65 },
        { name: "Molosses de Khorne", cost: 75 },
        { name: "Mutileur sur Trône de Sang", cost: 165 },
        { name: "Nurglings", cost: 40 },
        { name: "Porte-vérole", cost: 55 },
        { name: "Portepestes", cost: 110 },
        { name: "Preneur de Crânes", cost: 85 },
        { name: "Prince Démon du Chaos", cost: 190 },
        { name: "Prince Démon du Chaos Ailé", cost: 180 },
        { name: "Rotigus", cost: 250 },
        { name: "Sanguinaires", cost: 110 },
        { name: "Scribe Avarieur", cost: 60 },
        { name: "Shalaxi Helbane", cost: 380 },
        { name: "Skarbrand", cost: 305 },
        { name: "Syll'esske", cost: 120 },
        { name: "Tissetranse", cost: 60 },
        { name: "Tourmenteuse", cost: 140 },
        { name: "Veneuses", cost: 80 }
    ],
    "Chaos Knights": [
        { name: "Chevalier Abominable", cost: 325 },
        { name: "Chevalier Pillard", cost: 335 },
        { name: "Chevalier Profanateur", cost: 335 },
        { name: "Chevalier Ruineur", cost: 350 },
        { name: "Chevalier Saccageur", cost: 335 },
        { name: "Chevalier Tyran", cost: 395 },
        { name: "Dogue Brigand", cost: 140 },
        { name: "Dogue Chasseur", cost: 140 },
        { name: "Dogue Exécuteur", cost: 130 },
        { name: "Dogue Karnivore", cost: 140 },
        { name: "Dogue Rabatteur", cost: 140 },
        { name: "Chaos Acastus Knight Asterius", cost: 765 },
        { name: "Chaos Acastus Knight Porphyrion", cost: 700 },
        { name: "Chaos Cerastus Knight Acheron", cost: 355 },
        { name: "Chaos Cerastus Knight Atrapos", cost: 355 },
        { name: "Chaos Cerastus Knight Castigator", cost: 355 },
        { name: "Chaos Cerastus Knight Lancer", cost: 355 },
        { name: "Chaos Questoris Knight Magaera", cost: 345 },
        { name: "Chaos Questoris Knight Styrix", cost: 345 },
        { name: "War Dog Moirax", cost: 150 }
    ],
    "Chaos Space Marines": [
        { name: "Abaddon le Fléau", cost: 280 },
        { name: "Accusateur Renégat", cost: 55 },
        { name: "Apôtre Noir", cost: 65 },
        { name: "Bande de Cultistes", cost: 50 },
        { name: "Couronne de Noctilithe", cost: 125 },
        { name: "Cuitiste Boutefeu", cost: 45 },
        { name: "Cultistes Maudits", cost: 90 },
        { name: "Cypher", cost: 90 },
        { name: "Élus", cost: 125 },
        { name: "Escouade de Gardes Renégats", cost: 70 },
        { name: "Escouade Terminator du Chaos", cost: 180 },
        { name: "Fabius Bile", cost: 85 },
        { name: "Ferrocentaurus", cost: 180 },
        { name: "Ferrocerberus", cost: 130 },
        { name: "Griffe Némésis", cost: 110 },
        { name: "Haarken Worldclaimer", cost: 90 },
        { name: "Havocs", cost: 125 },
        { name: "Hommes-bêtes Affregors", cost: 70 },
        { name: "Huron Blackheart", cost: 80 },
        { name: "Land Raider du Chaos", cost: 240 },
        { name: "Légionnaires", cost: 90 },
        { name: "Maitre de la Possession", cost: 60 },
        { name: "Maître des Exécutions", cost: 80 },
        { name: "Métabrutus", cost: 130 },
        { name: "Métadrak", cost: 205 },
        { name: "Métaragne", cost: 120 },
        { name: "Motards du Chaos", cost: 70 },
        { name: "Obliterators", cost: 160 },
        { name: "Possédés", cost: 120 },
        { name: "Predator Annihilator du Chaos", cost: 135 },
        { name: "Predator Destructor du Chaos", cost: 140 },
        { name: "Prince Démon de l'Hereticus Astartes", cost: 165 },
        { name: "Prince Démon de l'Hereticus Astartes Ailé", cost: 180 },
        { name: "Profanateur", cost: 190 },
        { name: "Rapaces", cost: 90 },
        { name: "Rejetons du Chaos", cost: 70 },
        { name: "Rhino du Chaos", cost: 75 },
        { name: "Seigneur de la Discorde sur Métarôdeur", cost: 160 },
        { name: "Seigneur des Cranes de Khorne", cost: 450 },
        { name: "Seigneur du Chaos", cost: 90 },
        { name: "Seigneur du Chaos à Réacteur Dorsal", cost: 80 },
        { name: "Seigneur du Chaos en Armure Terminator", cost: 95 },
        { name: "Serres du Warp", cost: 125 },
        { name: "Sombre Communion", cost: 80 },
        { name: "Sorcier", cost: 60 },
        { name: "Sorcier en Armure Terminator", cost: 80 },
        { name: "Techmancien", cost: 70 },
        { name: "Vashtorr l'Arkifane", cost: 175 },
        { name: "Vindicator du Chaos", cost: 185 }
    ],
    "Dark Angels": [
        { name: "Asmodai", cost: 70 },
        { name: "Azraël", cost: 115 },
        { name: "Bélial", cost: 85 },
        { name: "Chasseur Néphilim", cost: 195 },
        { name: "Chevaliers de la Deathwing", cost: 250 },
        { name: "Chevaliers Noirs de la Ravenwing", cost: 90 },
        { name: "Compagnons du Cercle Intérieur", cost: 90 },
        { name: "Dark Talon de la Ravenwing", cost: 210 },
        { name: "Darkshroud de la Ravenwing", cost: 115 },
        { name: "Escouade d'État-major de la Ravenwing", cost: 120 },
        { name: "Escouade Terminator de la Deathwing", cost: 180 },
        { name: "Ézékiel", cost: 75 },
        { name: "Land Speeder Vengeance", cost: 120 },
        { name: "Lazarus", cost: 70 },
        { name: "Lion El'Jonson", cost: 315 },
        { name: "Sammael", cost: 115 }
    ],
    "Death Guard": [
        { name: "Biologus Putréfacteur", cost: 45 },
        { name: "Chenillé Crachepeste", cost: 195 },
        { name: "Chirurgien de la Peste", cost: 50 },
        { name: "Corrupteur Nidoreux", cost: 60 },
        { name: "Délabreur Délétère", cost: 50 },
        { name: "Drone Fétide", cost: 90 },
        { name: "Drone Fétide avec Lance-peste Lourd", cost: 100 },
        { name: "Essaimeur Répugnant", cost: 60 },
        { name: "Exhausteur Pandémique", cost: 105 },
        { name: "Intendant", cost: 40 },
        { name: "Land Raider du Chaos", cost: 240 },
        { name: "Marines de la Peste", cost: 95 },
        { name: "Métabrutus", cost: 115 },
        { name: "Mortarion", cost: 380 },
        { name: "Porte-icône", cost: 45 },
        { name: "Predator Annihilator du Chaos", cost: 135 },
        { name: "Predator Destructor du Chaos", cost: 145 },
        { name: "Prince Démon de Nurgle", cost: 195 },
        { name: "Prince Démon de Nurgle ailé", cost: 195 },
        { name: "Profanateur", cost: 165 },
        { name: "Rejetons du Chaos de Nurgle", cost: 80 },
        { name: "Rhino du Chaos", cost: 85 },
        { name: "Seigneur de la Contagion", cost: 110 },
        { name: "Seigneur de la Virulence", cost: 90 },
        { name: "Seigneur des Véroles", cost: 75 },
        { name: "Semi-chenillés Méphitiques", cost: 90 },
        { name: "Terminators du Linceul", cost: 40 },
        { name: "Terminators Rouillarques", cost: 115 },
        { name: "Typhus", cost: 90 },
        { name: "Véroleux", cost: 60 }
    ],
    "Deathwatch": [
        { name: "Capitaine du Guet Artemis", cost: 65 },
        { name: "Corvus Blackstar", cost: 180 },
        { name: "Escouade Terminator de la Deathwatch", cost: 190 },
        { name: "Kill Team Fortis", cost: 200 },
        { name: "Kill Team Indomitor", cost: 270 },
        { name: "Kill Team Spectrus", cost: 200 },
        { name: "Kill Team Talonstrike", cost: 290 },
        { name: "Maître du Guet", cost: 105 },
        { name: "Vétérans de la Deathwatch", cost: 100 }
    ],
    "Drukhari": [
        { name: "Archonte", cost: 85 },
        { name: "Belluaire", cost: 120 },
        { name: "Bombardier Korvide", cost: 235 },
        { name: "Cérastes", cost: 80 },
        { name: "Chasseur Stymphale", cost: 170 },
        { name: "Cour de l'Archonte", cost: 95 },
        { name: "Cronos", cost: 50 },
        { name: "Drazhar", cost: 85 },
        { name: "Ecumeurs", cost: 65 },
        { name: "Fléaux", cost: 130 },
        { name: "Gorgones", cost: 55 },
        { name: "Grotesques", cost: 80 },
        { name: "Guerriers Kabalites", cost: 100 },
        { name: "Hellions", cost: 75 },
        { name: "Hémoncule", cost: 60 },
        { name: "Incubes", cost: 85 },
        { name: "Lelith Hesperax", cost: 95 },
        { name: "Mandragores", cost: 65 },
        { name: "Ravageur", cost: 100 },
        { name: "Saccageur", cost: 75 },
        { name: "Succube", cost: 45 },
        { name: "Talos", cost: 80 },
        { name: "Urien Rakarth", cost: 80 },
        { name: "Venom", cost: 65 }
    ],
    "Emperor's Children": [
        { name: "Ferrocerberus", cost: 130 },
        { name: "Fulgrim", cost: 365 },
        { name: "Infracteurs", cost: 85 },
        { name: "Lames Infaillibles", cost: 110 },
        { name: "Land Raider du Chaos", cost: 240 },
        { name: "Lucius l'Éternel", cost: 150 },
        { name: "Marines du Vacarme", cost: 145 },
        { name: "Métadrak", cost: 195 },
        { name: "Prince Démon de Slaanesh", cost: 195 },
        { name: "Prince Démon de Slaanesh ailé", cost: 200 },
        { name: "Rejetons du Chaos", cost: 80 },
        { name: "Rhino du Chaos", cost: 80 },
        { name: "Seigneur Exultant", cost: 80 },
        { name: "Seigneur Kakophoniste", cost: 60 },
        { name: "Sorcier", cost: 60 },
        { name: "Terminators du Chaos", cost: 170 },
        { name: "Tourmenteurs", cost: 85 }
    ],
    "Genestealer Cults": [
        { name: "Aberrants", cost: 135 },
        { name: "Abominant", cost: 95 },
        { name: "Acolyte Garde-icône", cost: 50 },
        { name: "Alphus Chacal", cost: 55 },
        { name: "Benefictus", cost: 70 },
        { name: "Biophagus", cost: 50 },
        { name: "Camion Goliath", cost: 85 },
        { name: "Chacals Atalans", cost: 75 },
        { name: "Clamavus", cost: 50 },
        { name: "Concasseur Goliath", cost: 120 },
        { name: "Genestealers Pure-souche", cost: 75 },
        { name: "Hybrides Acolytes avec Lance-flammes Légers", cost: 70 },
        { name: "Hybrides Acolytes avec Pistolets-mitrailleurs", cost: 65 },
        { name: "Hybrides Métamorphes", cost: 80 },
        { name: "Hybrides Néophytes", cost: 65 },
        { name: "Kelermorphe", cost: 60 },
        { name: "Locus", cost: 45 },
        { name: "Magus", cost: 50 },
        { name: "Nexos", cost: 60 },
        { name: "Patriarche", cost: 75 },
        { name: "Primus", cost: 80 },
        { name: "Saboteur Reductus", cost: 65 },
        { name: "Sanctus", cost: 50 },
        { name: "Tout-terrain Achilles", cost: 85 }
    ],
    "Grey Knights": [
        { name: "Archiviste de Confrérie", cost: 120 },
        { name: "Castellan Crowe", cost: 90 },
        { name: "Champion de Confrérie", cost: 70 },
        { name: "Chapelain de Confrérie", cost: 75 },
        { name: "Cuirassier Némésis", cost: 210 },
        { name: "Dreadnought Vénérable des Grey Knights", cost: 155 },
        { name: "Escorteur Stormraven des Grey Knights", cost: 280 },
        { name: "Escorteur Stormtalon des Grey Knights", cost: 170 },
        { name: "Escouade d'Incursion", cost: 120 },
        { name: "Escouade Interceptor", cost: 125 },
        { name: "Escouade Paladin", cost: 215 },
        { name: "Escouade Purgator", cost: 120 },
        { name: "Escouade Purificator", cost: 125 },
        { name: "Escouade Terminator de Confrérie", cost: 200 },
        { name: "Frère-capitaine", cost: 90 },
        { name: "Frère-capitaine Stern", cost: 90 },
        { name: "Grand Maître", cost: 95 },
        { name: "Grand Maître en Cuirasse Némésis", cost: 210 },
        { name: "Grand Maître Voldus", cost: 95 },
        { name: "Intercepteur Stormhawk des Grey Knights", cost: 160 },
        { name: "Kaldor Draigo", cost: 125 },
        { name: "Land Raider Crusader des Grey Knights", cost: 220 },
        { name: "Land Raider des Grey Knights", cost: 240 },
        { name: "Land Raider Redeemer des Grey Knights", cost: 285 },
        { name: "Razorback des Grey Knights", cost: 85 },
        { name: "Rhino des Grey Knights", cost: 75 },
        { name: "Servitors", cost: 50 },
        { name: "Techmarine de Confrérie", cost: 70 },
        { name: "Grey Knights Thunderhawk Gunship", cost: 805 },
        { name: "Land Raider Banisher", cost: 255 }
    ],
    "Agents of the Imperium": [
        { name: "Agents Inquisitoriaux", cost: 50 },
        { name: "Assassin Callidus", cost: 100 },
        { name: "Assassin Culexus", cost: 85 },
        { name: "Assassin Eversor", cost: 110 },
        { name: "Assassin Vindicare", cost: 110 },
        { name: "Capitaine du Guet Artemis", cost: 65 },
        { name: "Chimera Inquisitorial", cost: 70 },
        { name: "Corvus Blackstar", cost: 180 },
        { name: "Cosmomarins en Armes", cost: 50 },
        { name: "Entourage de Libre Marchand", cost: 75 },
        { name: "Escouade d'Exaction", cost: 90 },
        { name: "Escouade de Sœurs de Bataille", cost: 100 },
        { name: "Escouade Subductor", cost: 85 },
        { name: "Escouade Terminator des Grey Knights", cost: 190 },
        { name: "Escouade Vigilant", cost: 85 },
        { name: "Immolator des Sœurs de Bataille", cost: 100 },
        { name: "Inquisiteur", cost: 55 },
        { name: "Inquisiteur Coteaz", cost: 75 },
        { name: "Inquisitrice Draxus", cost: 75 },
        { name: "Inquisitrice Greyfax", cost: 65 },
        { name: "Kill Team de la Deathwatch", cost: 100 },
        { name: "Maître du Guet", cost: 105 },
        { name: "Navigateur", cost: 60 },
        { name: "Prêtre du Ministorum", cost: 40 },
        { name: "Rhino Impérial", cost: 75 },
        { name: "Sanctificateurs", cost: 100 },
        { name: "Sapeurs de la Marine Impériale", cost: 90 }
    ],
    "Imperial Knights": [
        { name: "Armigères Hastaires", cost: 140 },
        { name: "Armigères Helvériens", cost: 130 },
        { name: "Canis Rex", cost: 380 },
        { name: "Chevalier Castellan", cost: 395 },
        { name: "Chevalier Croisé", cost: 365 },
        { name: "Chevalier Errant", cost: 345 },
        { name: "Chevalier Galant", cost: 345 },
        { name: "Chevalier Paladin", cost: 345 },
        { name: "Chevalier Précepteur", cost: 335 },
        { name: "Chevalier Vaillant", cost: 395 },
        { name: "Chevalier Vigilant", cost: 365 },
        { name: "Acastus Knight Asterius", cost: 765 },
        { name: "Acastus Knight Porphyrion", cost: 700 },
        { name: "Armiger Moirax", cost: 150 },
        { name: "Cerastus Knight Acheron", cost: 365 },
        { name: "Cerastus Knight Atrapos", cost: 365 },
        { name: "Cerastus Knight Castigator", cost: 365 },
        { name: "Cerastus Knight Lancer", cost: 365 },
        { name: "Questoris Knight Magaera", cost: 355 },
        { name: "Questoris Knight Styrix", cost: 355 }
    ],
    "Leagues of Votann": [
        { name: "Átregardes Einhyrs", cost: 150 },
        { name: "Beserks Cthoniens", cost: 100 },
        { name: "Champion Einhyr", cost: 60 },
        { name: "Forteresse Mobile Hekaton", cost: 225 },
        { name: "Grimnyr", cost: 65 },
        { name: "Guerriers Åtrekogs", cost: 100 },
        { name: "Kähl", cost: 70 },
        { name: "Maître-fer Brokhyr", cost: 65 },
        { name: "Pionniers Hernkogs", cost: 90 },
        { name: "Sagitaur", cost: 115 },
        { name: "Tonnekogs Brökhyrs", cost: 80 },
        { name: "Úthar le Destiné", cost: 80 },
        { name: "Yaegirs Hernkogs", cost: 90 }
    ],
    "Necrons": [
        { name: "Arachnydes Canopteks", cost: 75 },
        { name: "Arche du Jugement Dernier", cost: 200 },
        { name: "Arche Fantôme", cost: 115 },
        { name: "C'tan Transcendant", cost: 295 },
        { name: "Chronomancien", cost: 65 },
        { name: "Console d'Annihilation", cost: 105 },
        { name: "Console de Commandement", cost: 120 },
        { name: "Convergence de Domination", cost: 60 },
        { name: "Crypte Tesseract", cost: 425 },
        { name: "Cryptoserfs", cost: 60 },
        { name: "Dépeceurs", cost: 60 },
        { name: "Destroyer Hexmark", cost: 75 },
        { name: "Destroyers Lokhusts", cost: 40 },
        { name: "Destroyers Lourds Lokhusts", cost: 55 },
        { name: "Destroyers Ophydiens", cost: 80 },
        { name: "Destroyers Skorpekhs", cost: 90 },
        { name: "Écharde C'tan du Dragon du Néant", cost: 300 },
        { name: "Echarde C'tan du Mystificateur", cost: 265 },
        { name: "Écharde C'tan du Nyctophore", cost: 305 },
        { name: "Factionnaires", cost: 85 },
        { name: "Faucheur", cost: 230 },
        { name: "Garde Royal", cost: 50 },
        { name: "Guerriers Nécrons", cost: 90 },
        { name: "Illuminor Szeras", cost: 165 },
        { name: "Immortels", cost: 70 },
        { name: "Imotekh le Seigneur des Tempêtes", cost: 100 },
        { name: "Le Roi Silencieux", cost: 420 },
        { name: "Maraudeur Canoptek", cost: 140 },
        { name: "Mécanoptères", cost: 75 },
        { name: "Moissonneur", cost: 145 },
        { name: "Monolithe", cost: 400 },
        { name: "Nuées de Scarabées Canopteks", cost: 40 },
        { name: "Obélisque", cost: 300 },
        { name: "Orikan le Devin", cost: 80 },
        { name: "Plasmancien", cost: 55 },
        { name: "Prétoriens du Triarcat", cost: 100 },
        { name: "Psychomancien", cost: 55 },
        { name: "Réanimateur Canoptek", cost: 75 },
        { name: "Rôdeur du Triarcat", cost: 110 },
        { name: "Seigneur Lokhust", cost: 80 },
        { name: "Seigneur Skorpekh", cost: 90 },
        { name: "Spectres Canopteks", cost: 110 },
        { name: "Technomancien", cost: 80 },
        { name: "Tétrarque", cost: 85 },
        { name: "Tétrarque avec Linceul de Translocalisation", cost: 85 },
        { name: "Traqueurs", cost: 60 },
        { name: "Trazyn l'Infini", cost: 75 },
        { name: "Seraptek Heavy Construct", cost: 540 }
    ],
    "Orks": [
        { name: "Bizarboy", cost: 65 },
        { name: "Blitza-bomba", cost: 115 },
        { name: "Boît'kitu", cost: 125 },
        { name: "Boosta-klata Kustom", cost: 70 },
        { name: "Boss de Guerre", cost: 75 },
        { name: "Boss de Guerre en Méga-armure", cost: 90 },
        { name: "Boss Dresseur", cost: 80 },
        { name: "Boss Dresseur sur Squigosaure", cost: 130 },
        { name: "Boss Snikrot", cost: 95 },
        { name: "Boyz", cost: 80 },
        { name: "Boyz Alpagueurs", cost: 95 },
        { name: "Boyz sur Squigliers", cost: 150 },
        { name: "Brikojet Mégach'nillé", cost: 75 },
        { name: "Buggy Fourre-squigs", cost: 95 },
        { name: "Chariot Boumdakka de lux'", cost: 70 },
        { name: "Chariot d'Guerre", cost: 160 },
        { name: "Chokboyz", cost: 65 },
        { name: "Dakkajet", cost: 135 },
        { name: "Dragsta Shokk", cost: 70 },
        { name: "Dred eud' la Mort", cost: 120 },
        { name: "Frimeurs", cost: 80 },
        { name: "Ghazghkull Thraka", cost: 235 },
        { name: "Gorkanaute", cost: 265 },
        { name: "Gretchins", cost: 40 },
        { name: "Gro'Bunker d'Boss", cost: 135 },
        { name: "Gros Mek", cost: 70 },
        { name: "Gros Mek avec Kanon Shokk", cost: 85 },
        { name: "Gros Mek en Méga-armure", cost: 90 },
        { name: "Kamion", cost: 70 },
        { name: "Kanons d'Mek", cost: 50 },
        { name: "Kariol' Kichass'", cost: 135 },
        { name: "Kariol' Kitu", cost: 155 },
        { name: "Kass'tanks", cost: 140 },
        { name: "Kasseurs", cost: 140 },
        { name: "Klat'jet Wazboum", cost: 175 },
        { name: "Kommandos", cost: 120 },
        { name: "Kopters d'La Mort", cost: 80 },
        { name: "Krabouilleur", cost: 800 },
        { name: "Kram'boyz", cost: 60 },
        { name: "Krama-bomba", cost: 125 },
        { name: "Médiboss", cost: 70 },
        { name: "Médiko", cost: 80 },
        { name: "Méganobz", cost: 70 },
        { name: "Mek", cost: 45 },
        { name: "Morkanaute", cost: 280 },
        { name: "Motards de Guerre", cost: 70 },
        { name: "Mozrog Skragbad", cost: 165 },
        { name: "Nobz", cost: 105 },
        { name: "Pillards", cost: 50 },
        { name: "Trike Morkitu", cost: 80 },
        { name: "Zarboy", cost: 60 },
        { name: "Zodgrod Wortsnagga", cost: 90 },
        { name: "Gargantuan Squiggoth", cost: 440 }
    ],
    // etc... pour les autres factions
};


const crusadeRules = {
    battleTraits: {
        Personnage: [
            { name: "Diriger en Première Ligne", desc: "Cette unité passe les tests de Moral automatiquement si elle est à 6\" d'une unité MONSTRE ou VÉHICULE amie qui n'est pas Ébranlée." },
            { name: "Immunisé aux Horreurs", desc: "Cette unité peut relancer les tests de Moral." },
            { name: "Grand Acquisiteur", desc: "Ajoutez 3 à la caractéristique de Contrôle d'Objectif de la figurine PERSONNAGE de cette unité." },
            { name: "Rôdeur Conquérant", desc: "Tant que cette unité est à portée d'un pion d'objectif, elle gagne l'aptitude Discrétion." },
            { name: "Constitution Héroïque", desc: "Ajoutez 1 à la caractéristique de PV de cette unité." },
            { name: "Duelliste", desc: "Le champ d'attraction de nimbus de force est amélioré. À chaque attaque de mêlée effectuée par une figurine ennemie qui cible cette unité, si l'attaquant est à portée d'Engagement de cette unité, il subit 1 blessure mortelle." }
        ],
        Vehicule: [ // Inclut Monstre et Véhicule
            { name: "Protections Durcies", desc: "Dans les environnements tordus de cette zone de guerre, cette unité a su renforcer ses protections. Les figurines de cette unité ont l'aptitude insensible à la Douleur 6+." },
            { name: "Présence Totémique", desc: "Cette unité est considérée comme une icône de la victoire par ses camarades. Chaque fois que cette unité contrôle un pion d'objectif, ajoutez 1 à la caractéristique de Contrôle d'Objectif de 1 figurine de cette unité." },
            { name: "Chasseur de Chars", desc: "À chaque attaque effectuée par une figurine de cette unité qui cible une unité VÉHICULE ennemie, vous pouvez relancer le jet de blessure." },
            { name: "Explorateur Obstiné", desc: "Les figurines de cette unité ne sont pas ralenties par les débris et les obstacles et ignorent toutes les règles qui pénalisent le mouvement ou les jets d'Avance pour le terrain difficile." },
            { name: "Lourdement Blindé", desc: "Soustraire 1 à la caractéristique de Dégâts des attaques de mêlée." },
            { name: "Faucheur", desc: "À chaque attaque de mêlée effectuée par une figurine de cette unité MONTRÉE, relancez tout jet de touche de 1." }
        ],
        Monstre: [ // Partage les mêmes que Véhicule
            { name: "Protections Durcies", desc: "Dans les environnements tordus de cette zone de guerre, cette unité a su renforcer ses protections. Les figurines de cette unité ont l'aptitude insensible à la Douleur 6+." },
            { name: "Présence Totémique", desc: "Cette unité est considérée comme une icône de la victoire par ses camarades. Chaque fois que cette unité contrôle un pion d'objectif, ajoutez 1 à la caractéristique de Contrôle d'Objectif de 1 figurine de cette unité." },
            { name: "Chasseur de Chars", desc: "À chaque attaque effectuée par une figurine de cette unité qui cible une unité VÉHICULE ennemie, vous pouvez relancer le jet de blessure." },
            { name: "Explorateur Obstiné", desc: "Les figurines de cette unité ne sont pas ralenties par les débris et les obstacles et ignorent toutes les règles qui pénalisent le mouvement ou les jets d'Avance pour le terrain difficile." },
            { name: "Lourdement Blindé", desc: "Soustraire 1 à la caractéristique de Dégâts des attaques de mêlée." },
            { name: "Faucheur", desc: "À chaque attaque de mêlée effectuée par une figurine de cette unité MONTRÉE, relancez tout jet de touche de 1." }
        ],
        Infantrie: [
            { name: "Résistance de Briscard", desc: "Les figurines de cette unité ont l'aptitude Insensible à la Douleur 6+." },
            { name: "Spectres des Ruines", desc: "Les figurines de cette unité ont l'aptitude Infiltrateurs." },
            { name: "Unis dans l'Adversité", desc: "Vous pouvez cibler cette unité avec le Stratagème Intervention Héroïque pour 0 PC, même si vous avez déjà ciblé une unité différente avec ce Stratagème." },
            { name: "Pillards", desc: "À chaque attaque d'une figurine de cette unité avec une arme de mêlée qui cible une unité qui est à portée d'un pion d'objectif, relancez tout jet de touche de 1." },
            { name: "Purificateurs", desc: "Si elle a déjà le mot-clé GRENADES, vous pouvez cibler cette unité avec le Stratagème Grenade pour 0PC." },
            { name: "Assaut de Terreur", desc: "Au début de la phase de Combat, choisissez 1 unité ennemie à Portée d'Engagement de cette unité. L'unité ennemie doit faire un test d'Ébranlement." }
        ],
        Cavalerie: [ // Mounted
            { name: "Cavaliers des Ruines", desc: "Ajoutez 2\" à la caractéristique de Mouvement des figurines de cette unité." },
            { name: "Offensive Tonitruante", desc: "Ajoutez 1 aux jets d'Avance et de Charge faits pour cette unité." },
            { name: "Assassins sur Selle", desc: "À chaque attaque de mêlée d'une figurine de cette unité qui cible la cible éligible la plus proche, améliorez de 1 la caractéristique de Pénétration d'Armure de l'attaque." },
            { name: "Briseurs de Lignes", desc: "Chaque fois que cette unité finit un mouvement de Charge, jusqu'à la fin du tour, les armes de mêlée dont sont équipées les figurines de cette unité ont l'aptitude [TOUCHES SOUTENUES 1]." },
            { name: "Charge Broyeuse", desc: "Chaque fois que cette unité finit un mouvement de Charge, choisissez 1 unité ennemie à Portée d'Engagement d'elle, puis jetez 1 D6 pour chaque figurine de cette unité qui est à Portée d'Engagement de l'unité ennemie; pour chaque 4+, l'unité ennemie subit 1 blessure mortelle." },
            { name: "Vitesse Étourdissante", desc: "Les figurines de cette unité ont l'aptitude Discrétion." }
        ]
    },
    weaponMods: [
        { name: "Finement Équilibrée", desc: "Améliorez de 1 la caractéristique de Capacité de Tir ou de Capacité de Combat de cette arme." },
        { name: "Brutale", desc: "Ajoutez 1 à la caractéristique de Force de cette arme." },
        { name: "Perce-Blindage", desc: "Améliorez de 1 la caractéristique de Pénétration d'Armure de cette arme." },
        { name: "Œuvre de Maître", desc: "Ajoutez 1 à la caractéristique de Dégâts de cette arme." },
        { name: "Héritage", desc: "Ajoutez 1 à la caractéristique d'Attaques de cette arme." },
        { name: "Précise", desc: "À chaque Blessure Critique causée par une attaque de cette arme, l'attaque a l'aptitude [PRÉCISION]." }
    ],
    relics: {
        artificer: [
            { name: "Boussole d'Artificier", desc: "Le porteur gagne l'aptitude Infiltrateurs.", cost: 1 },
            { name: "Voile des Doyens", desc: "Le porteur gagne l'aptitude Infiltrateurs.", cost: 1 },
            { name: "Trésor des Technomandrites", desc: "Choisissez 1 arme dont est équipé le porteur. Chaque fois que cette arme est remplacée par une Optimisation ou une Relique de Croisade, notez-le. L'arme d'origine est considérée comme un évocateur.", cost: 1 },
            { name: "Armure de la Sentinelle sans Âme", desc: "Améliorez de 1 les caractéristiques d'Endurance et de Sauvegarde du porteur.", cost: 1 }
        ],
        antique: [
            { name: "Sceau de Noctilithe", desc: "Figurine non-PSYKER seulement. Les figurines du porteur ont l'aptitude Insensible à la Douleur 4+ contre les Attaques Psychiques.", cost: 2 },
            { name: "Clé-Dolmen", desc: "Le porteur peut se déployer via les tunnels Dolmen (Deep Strike).", cost: 2 },
            { name: "Miroir de Vantachren", desc: "Les figurines du porteur ont l'aptitude Discrétion. De plus, chaque fois qu'un porteur cible une unité ennemie avec une charge, soustrayez 2 au jet de Charge.", cost: 2 },
            { name: "Œil de Mars", desc: "Après que les joueurs ont déployé leurs armées, vous pouvez placer le porteur en Réserves Stratégiques.", cost: 2 }
        ],
        legendaire: [
            { name: "Lame du Dynaste", desc: "Améliorez de 1 les caractéristiques de Force, de Dégâts et de Pénétration d'Armure des armes de mêlée du porteur. Une fois par bataille, vous pouvez activer cette Relique pour ajouter 2 aux jets de Charge.", cost: 3 },
            { name: "Bouclier Noctique", desc: "Ajoutez 1 aux caractéristiques d'Endurance et de Points de Vie du porteur. Une fois par bataille, quand une attaque cible l'unité du porteur, il peut soustraire 1 à la caractéristique de Dégâts de l'attaque.", cost: 3 },
            { name: "Bâton de l'Omnimessie", desc: "Au début de votre phase de Commandement, le porteur récupère jusqu'à D3 PV perdus. Une fois par bataille, il peut choisir 1 unité ennemie à Portée d'Engagement du porteur. L'unité ennemie subit autant de blessures mortelles que le nombre de PV que le porteur a récupéré.", cost: 3 }
        ]
    },
    sombrerocheHonours: [
        { name: "Carte Nodale", desc: "Tant que le porteur est à portée d'un pion d'objectif, si l'unité du porteur est Ébranlée, remplacez par 1 au lieu de 0 la caractéristique de Contrôle d'Objectif des figurines.", cost: 20 },
        { name: "Chercheur Obsessionnel", desc: "Si le porteur est votre SEIGNEUR DE GUERRE, à la fin de la bataille, jetez 1 D6. En ajoutant 2 au jet si vous avez remporté la bataille. Sur 6+, vous gagnez 5 Fragments de Sombreroche.", cost: 10 },
        { name: "Opportuniste Cupide", desc: "Au début de la bataille, si le porteur est votre SEIGNEUR DE GUERRE, vous pouvez choisir une Posture Stratégique : Agressive (Aptitude Éclaireurs 6), Équilibrée (Aptitude Agent Solitaire), ou Défensive (Aptitude Discrétion).", cost: 15 }
    ],
    sombrerocheRelics: [
        { name: "Désincitateur Empathique", desc: "Au début de la bataille, choisissez 1 pion d'objectif. Tant que le porteur est sur le champ de bataille, les unités amies à portée du pion d'objectif ont une sauvegarde invulnérable de 5+.", cost: 15 },
        { name: "Armement de Noctilithe", desc: "Choisissez 1 arme de mêlée dont est équipé le porteur. Une fois par tour, à la fin de la phase de Combat, vous pouvez activer cette Relique de Croisade. Dans ce cas, jusqu'à la fin de la phase, à chaque attaque de cette arme, on ne peut pas faire de jet de sauvegarde invulnérable contre l'attaque.", cost: 20 },
        { name: "Amulette de Sombreroche", desc: "Chaque fois qu'une attaque de mêlée non modifiée de 6 est allouée au porteur, l'unité attaquante subit 1 blessure mortelle après qu'elle a résolu ses attaques. Si l'attaque avait été faite avec une arme Psychique, cet effet s'applique sur un jet de sauvegarde non modifié de 5+ à la place.", cost: 20 }
    ],
    battleScars: [
        { name: "Dégâts Invalidants", desc: "Cette unité ne peut pas Avancer et on soustrait 1\" à la caractéristique de Mouvement de ses figurines." },
        { name: "Usé par la Guerre", desc: "Chaque fois que cette unité fait un test d'Ébranlement, de Commandement, de Fuite Désespérée ou de Mise Hars de Combat, soustrayez 1 au test." },
        { name: "Épuisé", desc: "Soustrayez 1 à la caractéristique de Contrôle d'Objectif des figurines de cette unité, et cette unité ne reçoit jamais de bonus de Charge." },
        { name: "Disgrâce", desc: "Vous ne pouvez pas utiliser de Stratagème pour affecter cette unité, et elle ne peut pas être Promise à la Grandeur." },
        { name: "Honni", desc: "Les jets de touche ne peuvent pas être relancés pour cette unité. Si elle est Attachée, cela ne s'applique pas aux unités amies et elle ne peut pas être Promise à la Grandeur." },
        { name: "Cicatrices Intérieures", desc: "À chaque Blessure Critique causée contre cette unité, l'attaque blesse automatiquement cette unité." }
    ]
};